### ISSUE TITLE
import error for skimage feature from skimage.feature import register_translation

### ISSUE THREAD

**Issue by Kumarsan201006** [zanpeeters/sims#2]
ImportError: cannot import name 'register_translation' from 'skimage.feature' (C:\Users\rahul\anaconda3\envs\sims\lib\site-packages\skimage\feature\__init__.py)

**Comment by zanpeeters** [comment]
Thank you for reporting. `register_translation` was moved to `phase_cross_correlation` in version 1.9 of scikit-image. Updated in v2.0.1.

**Comment by zanpeeters** [comment]
Please use v2.0.2, the previous version used the wrong scikit-image version.
